name: Build

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - v*
  pull_request:
    branches:
      - main
      - release-*

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
        with:
          node-version: 22
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: package can be built
        run: wasm-pack build # --TODO: fix with --target web
        working-directory: wasmcloud-rs-js
      # - run: npm install
      # - run: npm run lint
      # - run: npm run build

      # - name: Is Release?
      #   if: startswith(github.ref, 'refs/tags/v')
      #   run: echo "DEPLOY_PACKAGE=true" >> $GITHUB_ENV

      # - name: Publish to npm
      #   if: env.DEPLOY_PACKAGE == 'true'
      #   run: npm pack && npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}